--Listar todos los registros por sucursal
CREATE PROCEDURE SP_L_CATEGORIA_01
@SUC_ID INT
AS
BEGIN
    SELECT * FROM TM_CATEGORIA
    WHERE
    SUC_ID = @SUC_ID
    AND EST=1
END

--OBTENER REGISTRO POR ID
CREATE PROCEDURE SP_L_CATEGORIA_02
@CAT_ID INT
AS
BEGIN
    SELECT * FROM TM_CATEGORIA
    WHERE
    CAT_ID = @CAT_ID
END

--ELIMINAR REGISTRO
CREATE PROCEDURE SP_D_CATEGORIA_01
@CAT_ID INT
AS
BEGIN
    UPDATE TM_CATEGORIA
    SET
        EST=0
    WHERE
    CAT_ID = @CAT_ID
END