--Listar todos los registros por sucursal
CREATE PROCEDURE SP_L_COMPANIA_01
@SUC_ID INT
AS
BEGIN
    SELECT * FROM TM_COMPANIA
    WHERE
    EST=1
END

--OBTENER REGISTRO POR ID
CREATE PROCEDURE SP_L_COMPANIA_02
@COM_ID INT
AS
BEGIN
    SELECT * FROM TM_COMPANIA
    WHERE
    COM_ID = @COM_ID
END

--ELIMINAR REGISTRO
CREATE PROCEDURE SP_D_COMPANIA_01
@COM_ID INT
AS
BEGIN
    UPDATE TM_COMPANIA
    SET
        EST=0
    WHERE
    COM_ID = @COM_ID
END

--REGISTRAR NUEVO REGISTRO
CREATE PROCEDURE SP_I_COMPANIA_01
@SUC_ID INT
@COM_NOM VARCHAR(150)
AS
BEGIN
    INSERT INTO TM_COMPANIA(
        COM_NOM,
        FECH_CREA,
        EST
    )
    VALUES(
        @COM_NOM,
        GETDATE(),
        1
    )
    END

--ACTUALIZAR REGISTRO
CREATE PROCEDURE SP_U_COMPANIA_01
@COM_ID INT,
@SUC_ID INT,
@COM_NOM VARCHAR(150)
AS
BEGIN
    UPDATE TM_COMPANIA
    SET
        SUC_ID = @SUC_ID,
        COM_NOM = @COM_NOM
    WHERE
        COM_ID = @COM_ID
END