--Listar todos los registros por sucursal
CREATE PROCEDURE SP_L_USUARIO_01
@SUC_ID INT
AS
BEGIN
    SELECT * FROM TM_USUARIO
    WHERE
    SUC_ID = @SUC_ID
    AND EST=1
END

--OBTENER REGISTRO POR ID
CREATE PROCEDURE SP_L_USUARIO_02
@USU_ID INT
AS
BEGIN
    SELECT * FROM TM_USUARIO
    WHERE
    USU_ID = @USU_ID
END

--ELIMINAR REGISTRO
CREATE PROCEDURE SP_D_USUARIO_01
@USU_ID INT
AS
BEGIN
    UPDATE TM_USUARIO
    SET
        EST=0
    WHERE
    USU_ID = @USU_ID
END

--REGISTRAR NUEVO REGISTRO
CREATE PROCEDURE SP_I_USUARIO_01
@SUC_ID INT
@USU_NOM VARCHAR(150)
AS
BEGIN
    INSERT INTO TM_USUARIO(
        SUC_ID,
        USU_NOM,
        FECH_CREA,
        EST
    )
    VALUES(
        @SUC_ID,
        @USU_NOM,
        GETDATE(),
        1
    )
    END

--ACTUALIZAR REGISTRO
CREATE PROCEDURE SP_U_USUARIO_01
@USU_ID INT,
@SUC_ID INT,
@USU_NOM VARCHAR(150)
AS
BEGIN
    UPDATE TM_USUARIO
    SET
        SUC_ID = @SUC_ID,
        USU_NOM = @USU_NOM
    WHERE
        USU_ID = @USU_ID
END